version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: car-inventory-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: car-inventory-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/car-inventory?authSource=admin
      JWT_SECRET: dev-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      UPLOAD_PATH: /app/uploads
      MAX_FILE_SIZE: 5242880
      CORS_ORIGIN: "*"
      LOG_LEVEL: info
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    command: sh -c "sleep 5 && npm run seed && npm start"

volumes:
  mongodb_data:
